resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
    - template: logicapp_template.yml